### ISSUE TITLE
Better explain breaker format

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-Breaker#1]
In

```
<record-identifier><tab><metadata-field><tab><metadata-value><tab><metadatavalue>...
```

what does `<metadatavalue>` mean? Could you add a textual description of the format? I'd remove the phrase "metadata" entirely (a "metadata-value" is just a value and a "metadata-field" is just a field). What about newlines and tabs in field values?

**Comment by phochste** [comment]
The breaker format isn't explained so this is what I came up with. The tab and newlines are escaped in the fieldvalues as \t and \n resp. 

The problem I'm more have is..that oai_dc is just one metadataFormat. I would also like to provide some statistics on MARC-ish data (or should I treat a breaker format just a triples "light"?)

**Comment by nichtich** [comment]
To me it looks like the format is only for flat formats (simple key-value) like CSV. But it could be extended in several ways I think of.

On 7. April 2016 20:32:45 MESZ, Patrick Hochstenbach notifications@github.com wrote:

> The breaker format isn't explained so this is what I came up with. The
> tab and newlines are escaped in the fieldvalues as \t and \n resp. 
> 
> The problem I'm more have is..that oai_dc is just one metadataFormat. I
> would also like to provide some statistics on MARC-ish data (or should
> I treat a breaker format just a triples "light"?)
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LibreCat/Catmandu-Breaker/issues/1#issuecomment-207040180

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
